# Generated by Django 2.2.5 on 2019-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191021_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='Author',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
