# Generated by Django 2.2.5 on 2019-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogcategoryindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='categorycolor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
