# Generated by Django 2.2.5 on 2020-01-07 20:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191030_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('BaseStream', wagtail.core.blocks.StreamBlock([('heads', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'H2'), ('h3', 'H3')]))])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(help_text='Insert a video url ', required=True))]))])), ('images', wagtail.core.blocks.StreamBlock([('heads', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))]))])), ('quoting', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(help_text='Add your text', required=True)), ('quotedby', wagtail.core.blocks.CharBlock(help_text='Quoted by', required=False))])), ('pages', wagtail.core.blocks.PageChooserBlock()), ('HTML', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
